apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: relay

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - api-hpa.yaml
  - worker-hpa.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: relay
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
