apiVersion: v1
kind: ConfigMap
metadata:
  name: relay-config
  namespace: relay
  labels:
    app.kubernetes.io/name: relay
data:
  REDIS_URL: "redis:6379"
  WORKER_CONCURRENCY: "10"
  AUTH_ENABLED: "true"
  ENABLE_PLAYGROUND: "false"
  METRICS_PROVIDER: "otel"
  SERVICE_NAME: "relay"
  ENVIRONMENT: "production"
